export * from "./skin-ownership.routes";
export * from "./skin-ownership.controller";
export * from "./skin-ownership.service";
export * from "./skin-ownership.domain";
export * from "./skin-ownership-source";
export * from "./skin-ownership.mapper";
export * from "./skin-ownership.dto";
export * from "./skin-ownership.repository";
export * from "./skin-ownership.model";